// <auto-generated />
using System;
using AgiloxSortingHall.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgiloxSortingHall.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415070155_SplitStationAreaNameIntoPickupAndDrop")]
    partial class SplitStationAreaNameIntoPickupAndDrop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("AgiloxSortingHall.Models.HallRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HallRows");
                });

            modelBuilder.Entity("AgiloxSortingHall.Models.HallSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DropRowSelectionStrategy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DropStationAreaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PickupStationAreaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RowSelectionStrategy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("HallSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DropRowSelectionStrategy = 1,
                            DropStationAreaName = "Hotovo",
                            PickupStationAreaName = "Buffer",
                            RowSelectionStrategy = 0
                        });
                });

            modelBuilder.Entity("AgiloxSortingHall.Models.PalletSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HallRowId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HallRowId", "PositionIndex")
                        .IsUnique();

                    b.ToTable("PalletSlots");
                });

            modelBuilder.Entity("AgiloxSortingHall.Models.RowCall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HallRowId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastAgiloxAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastAgiloxStatus")
                        .HasColumnType("TEXT");

                    b.Property<long?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkTableId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HallRowId");

                    b.HasIndex("WorkTableId");

                    b.ToTable("RowCalls");
                });

            modelBuilder.Entity("AgiloxSortingHall.Models.WorkTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputStationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputStationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkTables");
                });

            modelBuilder.Entity("AgiloxSortingHall.Models.PalletSlot", b =>
                {
                    b.HasOne("AgiloxSortingHall.Models.HallRow", "HallRow")
                        .WithMany("Slots")
                        .HasForeignKey("HallRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HallRow");
                });

            modelBuilder.Entity("AgiloxSortingHall.Models.RowCall", b =>
                {
                    b.HasOne("AgiloxSortingHall.Models.HallRow", "HallRow")
                        .WithMany()
                        .HasForeignKey("HallRowId");

                    b.HasOne("AgiloxSortingHall.Models.WorkTable", "WorkTable")
                        .WithMany()
                        .HasForeignKey("WorkTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HallRow");

                    b.Navigation("WorkTable");
                });

            modelBuilder.Entity("AgiloxSortingHall.Models.HallRow", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
